### ISSUE TITLE
part 3 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/William-Norfolk-Project#2]
My various comments, listed in no particular order:

I did not encounter any problems running your various bits of code.

I don’t think I fully understand your question regarding the citizen science bit. It’s unclear to me how exactly you want to determine if/how citizens report information that is similar to other sources. I also don’t quite understand what your tree predicts as outcome. In general, if you want to compare how 2 different sources agree/disagree, people talk about ‘inter-rater reliability’. If you are not familiar with that, maybe take a look here to see how people assess that:
https://en.wikipedia.org/wiki/Inter-rater_reliability
It’s usually just simple correlation tests for the same outcome for different raters. 

Your problem might be that you don’t have exactly the same outcome rated by 2 different entities? Again, I’m not fully sure what exactly you are after. Conceptually, think of a tree model like a linear or logistic regression model, just using a different approach. So if for your question you could in principle use a linear or logistic model to answer it, then a tree is ok too. Details regarding the data and other considerations (e.g. ease of understanding) can then determine which one to prefer. 

I’d be happy to take another look at this question once you update things and add some more details.

If you want more feedback on specific aspects, let me know either by replying to this Issue or email.

**Comment by williamnorfolk** [comment]
Thank you for your feedback Dr. Handel! 

The inter-rater reliability is exactly the kind of analysis I was searching for to answer this question so I appreciate the direction.  I am still very interested in addressing the efficacy of the citizen science data (as are my collaborators at MarineLab) however, I agree with you that this would require a second rater to compare. I found another water quality database that is maintained by the Florida Keys National Marine Sanctuary; many of the sites overlap with the same/similar locations that are sampled in the citizen science data. Would it be appropriate to compare the citizen science data to the sanctuary data (subsetted to only include Key Largo measurements)? 

Since inter-rater reliability will take the place of my previous tree model, I will incorporate a new tree model into my seasonal analysis to ensure my project still retains a modeling component.

Thanks again for the feedback!
